### ISSUE TITLE
BIOS crashes on Key Management Page

### ISSUE THREAD

**Issue by nair1** [perez987/OpenCore-and-UEFI-Secure-Boot#11]
I followed the guide step-by-step and got to [this step](https://github.com/perez987/OpenCore-and-UEFI-Secure-Boot#bios), but as soon as I tried to hit `Update`, the BIOS just froze. I restarted my PC and now whenever I enter the Key Management Page under secure boot, it freezes. I can't enable or disable secure boot either since that option is located in the Key Management Page.

At this point, I'm just trying to get back to a working state. I can still boot into Windows 11 thankfully, but I can't get around this BIOS issue. I've tried flashing to the latest BIOS and even removing the battery for an hour and shorting the jumper. Do I have any other options here?

**Comment by nair1** [comment]
Update: While I wasn't able to fix the root issue of broken secure boot keys, ASUS BIOS has a handy "my favorites" tab where you can add any action without physically navigating to that menu. Luckily, they had an action for "clear secure boot keys" which you can access without going through the Key Management page, so I was able to use that to get back to a working state.

I'm still looking for a solution to the actual issue however.

**Comment by perez987** [comment]
@nair1 
Sorry for the delayed answer.
Something has gone wrong when you updated keys in the BIOS. Not know why.
The only fix I have is to completely clear CMOS to go back to its original state. As a BIOS factory reset. But you say that you have already made this without success.
Clear the CMOS in your motherboard shorting a couple of pins (done). Or unplug the PC, open the case and remove the motherboard battery for a few seconds (also done).

No more ideas.

Are you able to disable UEFI Secure Boot without entering the key management?

How can it happen? What you have done can't keep any setting made after factory. Including any secure keys management.

Remember that you can use Append with db.auth and kek.auth but pk.auth only allows replacement (Update button).

**Comment by perez987** [comment]
@nair1 
Are you able to fix something using KeyTool.efi instead of the BIOS menu?

**Comment by nair1** [comment]
Busy today but I’ll try the KeyTool instead tomorrow. There’s a chance I just messed up one of the steps along the way. 

I’m not too familiar with how keys are stored, but I’m not understanding how they could persist even after clearing CMOS and shorting the jumper. Unless it has some kind of onboard memory that doesn’t require any power to retain info, it shouldn’t keep those keys after. Either way, I’m glad ASUS has an unconventional workaround to get to the “clear keys” menu option

**Comment by perez987** [comment]
@nair1 
You say `I’m not understanding how they could persist even after clearing CMOS and shorting the jumper` and this is also my thought. Understandable.
KeyTool is a different way to access the key store but I'm not confident in the success, anyway try it.
I asked you if you can disable UEFI Secure Boot to be able to boot macOS.
Sorry for the inconveniences.

**Comment by nair1** [comment]
Yup, I can still boot into macOS with it disabled, I just have to keep switching it every time I boot to windows 11 to do things that require secure boot. 

It’s not a huge issue if I can’t figure this out, but I’ll give KeyTool a shot tomorrow

**Comment by perez987** [comment]
@nair1 
Have you been able to fix this issue in any way?

**Comment by nair1** [comment]
KeyTool seemed to update the keys, but I’m still getting a secure boot error when trying to boot to macOS.

Honestly, it’s not too much of an issue. I just have to remember to clear/install keys when switching between OSes

**Comment by perez987** [comment]
@nair1 
Sorry for the inconvenience. 
Closing the issue as not complered.

**Comment by perez987** [comment]
@nair1
Sorry for the inconvenience.
Closing the issue as not completed.

**Comment by perez987** [comment]
@nair1
Sorry for the inconvenience.
Closing the issue for now.
