### ISSUE TITLE
HfsPlus.efi is not being signed with sign_opencore.sh script

### ISSUE THREAD

**Issue by DaniHv** [perez987/OpenCore-and-UEFI-Secure-Boot#5]
Since the HfsPlus.efi file is located at /Downloaded/HfsPlus.efi, and that path doesn't match the pattern of the script: ./Downloaded/X64/EFI/**/*, the HfsPlus.efi is not being signed.

A solution would be either:
1- Set the download target HfsPlus.efi to /Downloaded/X64/EFI/OC/Drivers/HfsPlus.efi (when using -O flag in wget command)
2-  Modify the pattern to: ./Downloaded/*

**Comment by perez987** [comment]
@DaniHv 
Buenas noches. Indeed is as you say, I changed the code at some point and I did not notice that HfsPlus path was wrong.
Now merging your PR.
¡Gracias!
