### ISSUE TITLE
Mac OS Partition is not detected after implementing UEFI Secureboot

### ISSUE THREAD

**Issue by OctoCharm** [perez987/OpenCore-and-UEFI-Secure-Boot#8]
I've followed your instructions carefully, and then replace all the EFI folder to my OpenCore EFI partition. I've also already append the DB and KEK and replacing the PK from my BIOS. It booted up to OpenCore.efi, but no Mac partition is present.

Strangely, when I do a local booting via Ventoy to my OpenCore's BOOTx64.efi (with secure boot activated), the Mac partition appears. But I don't know what causing this problem.

As an additional information, Ventoy uses shim in order to enroll their MOK cert, but I don't know if this has any correlation with the implementation of OpenCore UEFI secure boot.

**Comment by perez987** [comment]
@OnePeach47 
Do you have Apple Secure Boot disabled? I mean, SecureBootModel=Disabled, DmgLoading=Any and no ApECID.

**Comment by perez987** [comment]
@OnePeach47 
Although it's not so obvious from reading these instructions, it appears that OpenCore does not allow access to APFS systems running macOS if UEFI Secure Boot is enabled but Apple Secure Boot is disabled. At least as of macOS 10.13, when Apple Secure Boot was released: chapter 12.2 UEFI Secure Boot of the OpenCore setup PDF.

It is also not possible to activate Apple Secure Boot on HFS+ systems.

In short, with Apple Secure Boot disabled, if you enable UEFI Secure Boot you cannot access APFS disks from OpenCore.

**Comment by 3arthur6** [comment]
You can try to enable _DisableSecurityPolicy_ and _ProtectUefiServices_ quirks.
I fixed a similar issue with these.

**Comment by perez987** [comment]
Yes, @OnePeach47 , you can do it enabling those 2 quirks as @3arthur6 says but it's an unsafe mode of operation.
